### PR TITLE
Fix(Advert): Overflow in web advert page

### LINKED ISSUE #293: Advert: Text overflow on web
image

### PR DESCRIPTION
**Pull request by guillaumetavernier**
Close #293

image
image

### CODE REVIEW

File: lib/advert/ui/components/advert_card.dart [hunk 1]
```diff
@@ -72,28 +72,38 @@ class AdvertCard extends HookConsumerWidget {
                       Expanded(
                         child: Column(
                           children: [
-                            Text(advert.title,
-                                textAlign: TextAlign.center,
-                                style: const TextStyle(
-                                  fontSize: 20,
-                                  fontWeight: FontWeight.bold,
-                                )),
+                            SingleChildScrollView(
```
Comment (maximeroucher) [inline lib/advert/ui/components/advert_card.dart:75]: Maybe the usage of an AutoSizeText with multiline is more appropriate for a title

File: lib/advert/ui/components/advert_card.dart [hunk 2]
```diff
@@ -72,28 +72,38 @@ class AdvertCard extends HookConsumerWidget {
...
+                            ),
                             const SizedBox(
                               height: 10,
                             ),
-                            Text(formatDate(advert.date),
-                                textAlign: TextAlign.center,
-                                style: const TextStyle(
-                                  fontSize: 16,
-                                )),
+                            SingleChildScrollView(
```
Comment (maximeroucher) [inline lib/advert/ui/components/advert_card.dart:87]: The same goes for the dates

**Review by maximeroucher — APPROVED** [review]

**Review by julien4215 — APPROVED** [review]
